// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkOItn9hMgKTnsuc4kxrSlm4nOIiffLI',
    appId: '1:579658096080:android:e0b0452a478d0126d6add5',
    messagingSenderId: '579658096080',
    projectId: 'suqyarahiq-app-173f2',
    storageBucket: 'suqyarahiq-app-173f2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHHF7TukQcRF4Fsv2C67El5iNd8qwxZg',
    appId: '1:579658096080:ios:8911d276db4f444fd6add5',
    messagingSenderId: '579658096080',
    projectId: 'suqyarahiq-app-173f2',
    storageBucket: 'suqyarahiq-app-173f2.firebasestorage.app',
    androidClientId: '579658096080-5onpmak5jbnbvhpkjlmmk4v1qkvv9m8p.apps.googleusercontent.com',
    iosClientId: '579658096080-9ltekehkrutd8cdem2i3rtl8d5mmpsq9.apps.googleusercontent.com',
    iosBundleId: 'com.rahiq.driver',
  );
}
